In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn import datasets

In [4]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [5]:
data.shape

(4, 3)

In [9]:
data[[0,3]]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [10]:
data[1:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
data[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [18]:
data[:,[0,2]]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])