In [15]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn import datasets
import seaborn as sns
from sklearn import preprocessing

In [8]:
data = sns.load_dataset('titanic')
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

### fare(승선가격),sex(성별)에 따른 생존유무를 예측하시요
#### w,b,를 구하고, 정확도를 구하시요.

In [35]:
xdata = data[['Sex_encode','fare']]
ydata = data['survived']

In [33]:
data.loc[data["sex"] == "male", "Sex_encode"] = 0
data.loc[data["sex"] == "female", "Sex_encode"] = 1
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       0       0   0.0      0      0   0.0000        0   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       0       0   0.0      0      0   0.0000        0   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       0       0   0.0      0      0   0.0000        0  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         0       0       0   0.0      0      0   0.0000        0   First   
890         0       0       0   0.0      0      0   0.0000        0   Third   

       who  adult_male deck  embark_town alive  alone  Sex_encode  
0      man        True  NaN  Southampton    no  False         0.0  
1    woman       False    C    Cherbourg   yes  False         1.0  
2    woman       False  NaN  Southampton   yes   True         1.0  
3    woman       False    C  Southampton   yes  False         1.0  
4      man        True  NaN  Southampton    no   True         0.0  
..     ...         ...  ...          ...   ...    ...         ...  
886    man        True  NaN  Southampton    no   True         0.0  
887  woman       False    B  Southampton   yes   True         1.0  
888  woman       False  NaN  Southampton    no  False         1.0  
889    man        True    C    Cherbourg   yes   True         0.0  
890    man        True  NaN   Queenstown    no   True         0.0  

[891 rows x 16 columns]

In [38]:
x = tf.placeholder(tf.float32,shape=[None,2])
y = tf.constant( ydata, tf.float32)
w = tf.Variable( tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

hx = tf.matmul(x,w) +b
cost = tf.reduce_mean ( tf.square(hx-y) )

optimizer = tf.train.AdamOptimizer(0.1) #Learning rate
train = optimizer.minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range( 1000):
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 869.2419
1 630.1445
2 431.57034
3 273.20883
4 153.9229
5 71.512405
6 22.517105
7 2.1099288
8 4.1953306
9 21.78513
10 47.65534
11 75.15561
12 98.947556
13 115.46604
14 123.01248
15 121.53892
16 112.24559
17 97.1258
18 78.54021
19 58.863216
20 40.213882
21 24.26646
22 12.135618
23 4.3332634
24 0.7905762
25 0.94136757
26 3.8555653
27 8.405412
28 13.440947
29 17.948725
30 21.171795
31 22.676308
32 22.361937
33 20.422026
34 17.268278
35 13.435669
36 9.48456
37 5.9146314
38 3.099533
39 1.249353
40 0.402311
41 0.443323
42 1.1436095
43 2.212791
44 3.3537543
45 4.311202
46 4.9064984
47 5.054966
48 4.764956
49 4.1216516
50 3.2601771
51 2.334415
52 1.4872884
53 0.82735676
54 0.4149139
55 0.25860366
56 0.32173872
57 0.535806
58 0.8177788
59 1.087493
60 1.2819116
61 1.364048
62 1.325618
63 1.1839297
64 0.9742926
65 0.7402261
66 0.523586
67 0.35654312
68 0.2567348
69 0.22605415
70 0.25276253
71 0.31603098
72 0.39159775
73 0.45726153
74 0.49706656
75 0.50356746
76 0.4779241
77 0.4282138
78 0.366542

In [39]:
sess.run(w)

array([[ 1.1359596e-08],
       [-4.2994258e-10]], dtype=float32)

In [40]:
sess.run(b)

array([0.26150396], dtype=float32)

In [43]:
result = sess.run(hx, {x:[[0,53]]})
result

array([[0.26150393]], dtype=float32)

In [41]:
xdata

Sex_encode     fare
0           0.0   0.0000
1           1.0  71.2833
2           1.0   7.9250
3           1.0  53.1000
4           0.0   0.0000
..          ...      ...
886         0.0   0.0000
887         1.0  30.0000
888         1.0  23.4500
889         0.0   0.0000
890         0.0   0.0000

[891 rows x 2 columns]