In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

In [6]:
arr = np.loadtxt('./data/data/softmax.txt')
arr
#CCC/BBB/AAA

array([[1., 2., 1., 0., 0., 1.],
       [1., 3., 2., 0., 0., 1.],
       [1., 3., 4., 0., 0., 1.],
       [1., 5., 5., 0., 1., 0.],
       [1., 7., 5., 0., 1., 0.],
       [1., 2., 5., 0., 1., 0.],
       [1., 6., 6., 1., 0., 0.],
       [1., 7., 7., 1., 0., 0.]])

In [11]:
xdata = arr[:,1:3]
ydata = arr[:,3:6]

In [13]:
xdata

array([[2., 1.],
       [3., 2.],
       [3., 4.],
       [5., 5.],
       [7., 5.],
       [2., 5.],
       [6., 6.],
       [7., 7.]])

In [12]:
ydata

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [14]:
x = tf.placeholder(tf.float32,[None,2])
y = tf.constant(ydata,tf.float32)

w = tf.Variable(tf.random_uniform([2,3]))
b = tf.Variable(tf.random_uniform([3]))

z = tf.matmul(x,w) + b
hx = tf.nn.softmax(z)
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits= z, labels=y) #logits 인자에는 hx함수 , labels= Tensor형 yvalue
cost = tf.reduce_mean(cost_i)

optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(1000):
    sess.run(train,{x:xdata})
    if i%100 == 99:
        print(i,sess.run(cost,{x:xdata}))
        

In [40]:
sess.run(w)

array([[ 0.65850204,  0.5197276 ,  0.37467965],
       [ 1.3843038 ,  0.75368214, -0.39033872]], dtype=float32)

In [41]:
sess.run(b)

array([-4.1159816,  0.3458137,  5.3677387], dtype=float32)

In [73]:
h = sess.run(hx,{x:[[6,6]]})
h

array([[0.52256423, 0.4477199 , 0.02971584]], dtype=float32)

In [74]:
hh = sess.run(hx,{x:[[6,6],[1,1]]})
hh

array([[5.2256477e-01, 4.4771948e-01, 2.9715808e-02],
       [5.8174384e-04, 2.3351802e-02, 9.7606647e-01]], dtype=float32)

In [75]:
hh.argmax(axis=1)

array([0, 2], dtype=int64)

In [76]:
h.argmax(axis = 1)

array([0], dtype=int64)

In [77]:
grade = ['A','B','C']
grade[int(h.argmax(axis = 1))]

'A'

# Argmax 설명

In [56]:
myarr = np.array([[1,2,3],[3,4,5]])

myarr.argmax() #index = 0,1,None ( 0: colume 별 , 1: row 별, None : 전체)