In [1]:
import tensorflow as tf

In [9]:
a = tf.constant([10,20])

In [10]:
b = tf.constant([1,2])

In [11]:
c = tf.subtract(a,b)

In [13]:
sess = tf.Session()

In [15]:
sess.run(c) #elementwise 연산 (요소별 연산)

array([ 9, 18])

In [16]:
d = tf.mod(a,b) # a % b

In [17]:
sess.run(d)

array([0, 0])

In [18]:
e = tf.divide(a,b)

In [19]:
sess.run(e)

array([10., 10.])